//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dependent
    {
        public short Id { get; set; }
        public string Name { get; set; }
        public System.Guid Employee { get; set; }
    
        public virtual Employee Employee1 { get; set; }
    }
}
